### ISSUE TITLE
modal forbidden scroll on mobile but click hide and unbind  scroll

### ISSUE THREAD

**Issue by mqliutie** [dreamochi/DayDayUp#36]
``` HTML
<button ng-click="vm.forHelp()">请求支援</button>
<div class="share" ng-show="vm.is_for_help"></div>
```

``` css
.share{
  position: absolute;
  z-index: 100;
  width: 100%;
  height: 100vh;
  background: url("@{static_path}/images/share.png") no-repeat 85% 5%;
  background-color: rgba(0,0,0,0.5) !important;
  background-size: 50% 36.5%;
}
```

``` js
function forHelp () {
    vm.is_for_help = true;
    var height = $ (document).scrollTop ();
    var share = $ ('.share');
    share.css ('top', height); //设置在当前位置显示modal
    share.on ('click', function () {
        vm.is_for_help = false;
        $ (document).unbind ('touchmove');
        $scope.$apply (); //非常重要,如果没这句话,状态不会更新
    });
    $ (document).bind ('touchmove', function (e) {
        e.preventDefault (); // 禁止掉可以滑动
    });
}
```
